[unstable]
build-std = ["core", "alloc"]

[target.bpfel-unknown-none]
rustflags = [
    "-C", "linker=sbpf-linker",
    "-C", "panic=abort",
    "-C", "link-arg=--llvm-args=-bpf-stack-size=4096",
    "-C", "relocation-model=static",
    # "--cfg", "feature=\"mem_unaligned\"", 
    # "-C", "link-arg=--disable-memory-builtins",
    # "-C", "link-arg=--disable-expand-memcpy-in-order",
    # "-C", "target-cpu=v2"
]

[alias]
build-bpf = "build --release --target bpfel-unknown-none"
